# Generated by Django 4.2.5 on 2023-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account_created', models.DateTimeField(verbose_name='account creation date')),
            ],
        ),
    ]
